#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

sed "/newrelic.license/s/.*/newrelic.license = \"$NEW_RELIC_LICENSE_KEY\"/" /etc/php/8.2/mods-available/newrelic.ini
sed "/newrelic.appname/s/.*/newrelic.appname = \"$NEW_RELIC_APP_NAME\"/" /etc/php/8.2/mods-available/newrelic.ini

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
